version: '3.4'

volumes:
  sg_data:
  sg_data_api_node_modules:
  sg_public_vendor:
  sg_admin_vendor:

services:
  postgres:
    container_name: sg_data_postgres
    image: postgres
    environment:
      - POSTGRES_DB=sg_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - sg_data:/var/lib/postgresql/data

  api:
    container_name: sg_data_api
    build:
      context: sg_data
      target: develop
    command: bash -c "npm run seed && nodemon --exec npm start --ignore docs/"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@sg_data_postgres:5432/sg_data
    volumes:
      - sg_data_api_node_modules:/app/node_modules
      - ./sg_data:/app
    depends_on:
      - postgres

  admin:
    container_name: sg_admin
    build:
      context: sg_admin
    command: php -S 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - sg_admin_vendor:/var/www/vendor
      - ./sg_admin:/var/www
    depends_on:
      - postgres
      - api

  public:
    container_name: sg_public
    build:
      context: sg_public
    command: php -S 0.0.0.0:8080
    ports:
      - 8080:8080
    volumes:
      - sg_public_vendor:/var/www/vendor
      - ./sg_public:/var/www
    depends_on:
      - postgres
      - api
